.PHONY: clean All

All:
	@echo "----------Building project:[ LinkedList_4 - Debug ]----------"
	@cd "LinkedList_4" && "$(MAKE)" -f  "LinkedList_4.mk"
clean:
	@echo "----------Cleaning project:[ LinkedList_4 - Debug ]----------"
	@cd "LinkedList_4" && "$(MAKE)" -f  "LinkedList_4.mk" clean
