.PHONY: clean All

All:
	@echo "----------Building project:[ Recursion_1 - Debug ]----------"
	@cd "Recursion_1" && "$(MAKE)" -f  "Recursion_1.mk"
clean:
	@echo "----------Cleaning project:[ Recursion_1 - Debug ]----------"
	@cd "Recursion_1" && "$(MAKE)" -f  "Recursion_1.mk" clean
