.PHONY: clean All

All:
	@echo "----------Building project:[ Stack_01 - Debug ]----------"
	@cd "Stack_01" && "$(MAKE)" -f  "Stack_01.mk"
clean:
	@echo "----------Cleaning project:[ Stack_01 - Debug ]----------"
	@cd "Stack_01" && "$(MAKE)" -f  "Stack_01.mk" clean
