.PHONY: clean All

All:
	@echo "----------Building project:[ Queue_1 - Debug ]----------"
	@cd "Queue_1" && "$(MAKE)" -f  "Queue_1.mk"
clean:
	@echo "----------Cleaning project:[ Queue_1 - Debug ]----------"
	@cd "Queue_1" && "$(MAKE)" -f  "Queue_1.mk" clean
