.PHONY: clean All

All:
	@echo "----------Building project:[ PathPlanning - Debug ]----------"
	@cd "PathPlanning" && "$(MAKE)" -f  "PathPlanning.mk"
clean:
	@echo "----------Cleaning project:[ PathPlanning - Debug ]----------"
	@cd "PathPlanning" && "$(MAKE)" -f  "PathPlanning.mk" clean
